apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy_django
  namespace: dev
spec:
  strategy: 				          # 策略
    type: RollingUpdate 			# 滚动更新策略
  replicas: 3
  selector:
    matchLabels:
      app: app_django
  template:
    metadata:
      labels:
        app: app_django
    spec:
      containers:
      - name: django
        image: victor/django:1.0
        imagePullPolicy: IfNotPresent
        resources: 			      # 资源配额
          limits:  			      # 限制资源（上限）
            cpu: "300m" 			    # CPU限制，单位是core数
            memory: "300Mib"
          requests: 			    # 请求资源（下限）
            cpu: "100m"  			# CPU限制，单位是core数
            memory: "100Mib"
        ports:
          - containerPort: 80