# hpa_django
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa_django
  namespace: dev
spec:
  minReplicas: 3  					# 最小pod数量
  maxReplicas: 10 					# 最大pod数量
  targetCPUUtilizationPercentage: 3 		# CPU使用率指标
  scaleTargetRef:   				# 指定要控制的信息
    apiVersion: apps/v1
    kind: Deployment
    name: deploy_django

---
# hpa_mysql
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa_mysql
  namespace: dev
spec:
  minReplicas: 2  					# 最小pod数量
  maxReplicas: 4 					# 最大pod数量
  targetCPUUtilizationPercentage: 3 		# CPU使用率指标
  scaleTargetRef:   				# 指定要控制的信息
    apiVersion: apps/v1
    kind: Deployment
    name: deploy_mysql

---
# hpa_redis
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa_redis
  namespace: dev
spec:
  minReplicas: 2  					# 最小pod数量
  maxReplicas: 4 					# 最大pod数量
  targetCPUUtilizationPercentage: 3 		# CPU使用率指标
  scaleTargetRef:   				# 指定要控制的信息
    apiVersion: apps/v1
    kind: Deployment
    name: deploy_redis